// @ts-check

/**
 * @typedef {"ciudad" | "villa" | "refugio" | "montana"} PointType
 */

/**
 * @typedef {Object} PointConfig
 * @property {string} id
 * @property {string} name
 * @property {string[]} aliases
 * @property {string} zone
 * @property {string} region
 * @property {PointType} type
 * @property {number} lat
 * @property {number} lon
 * @property {number | null} altitudeM
 * @property {"primary" | "secondary" | "reference"} priority
 * @property {string[]} outingTags
 * @property {string[]} exposureTags
 * @property {{ spotId?: number, label?: string, precision?: "exact" | "nearby" | "area" } | null} windguru
 * @property {string} coordinatesSource
 * @property {string | null} altitudeSource
 */

/** @type {PointConfig[]} */
export const points = [
  {
    id: "buenos-aires",
    name: "Buenos Aires",
    aliases: ["CABA", "Capital Federal", "Ciudad de Buenos Aires"],
    zone: "Buenos Aires",
    region: "buenos-aires",
    type: "ciudad",
    lat: -34.6083696,
    lon: -58.4440583,
    altitudeM: null,
    priority: "reference",
    outingTags: ["urbano", "referencia", "base"],
    exposureTags: ["urbano", "llanura"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "bariloche-centro",
    name: "San Carlos de Bariloche",
    aliases: ["Bariloche", "Centro", "Ciudad"],
    zone: "Bariloche urbano",
    region: "bariloche",
    type: "ciudad",
    lat: -41.1334781,
    lon: -71.3101474,
    altitudeM: null,
    priority: "primary",
    outingTags: ["base", "urbano", "logistica"],
    exposureTags: ["lago", "valle"],
    windguru: { spotId: 141627, label: "Argentina - Bariloche", precision: "area" },
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "villa-catedral",
    name: "Villa Catedral",
    aliases: ["Catedral", "Base Catedral", "Cerro Catedral"],
    zone: "Cerro Catedral",
    region: "bariloche",
    type: "villa",
    lat: -41.1652469,
    lon: -71.4394927,
    altitudeM: null,
    priority: "primary",
    outingTags: ["base", "esqui", "trekking"],
    exposureTags: ["montana", "viento"],
    windguru: { spotId: 1012563, label: "Argentina - Villa Catedral", precision: "nearby" },
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "villa-llao-llao",
    name: "Villa Llao Llao",
    aliases: ["Llao Llao", "Circuito Chico"],
    zone: "Llao Llao",
    region: "bariloche",
    type: "villa",
    lat: -41.0539926,
    lon: -71.5239328,
    altitudeM: null,
    priority: "primary",
    outingTags: ["bosque", "miradores", "lagos"],
    exposureTags: ["bosque", "lago"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "el-bolson",
    name: "El Bolsón",
    aliases: ["Bolson", "Centro Bolsón"],
    zone: "El Bolsón",
    region: "bolson",
    type: "ciudad",
    lat: -41.9649027,
    lon: -71.5348197,
    altitudeM: null,
    priority: "primary",
    outingTags: ["base", "logistica", "valle"],
    exposureTags: ["valle", "urbano"],
    windguru: { spotId: 166542, label: "Argentina - El Bolsón", precision: "area" },
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "villa-la-angostura",
    name: "Villa La Angostura",
    aliases: ["La Angostura", "VLA"],
    zone: "Nahuel Huapi norte",
    region: "angostura",
    type: "villa",
    lat: -40.7620693,
    lon: -71.6472306,
    altitudeM: null,
    priority: "primary",
    outingTags: ["base", "bosque", "lagos"],
    exposureTags: ["bosque", "lago"],
    windguru: { spotId: 996095, label: "Argentina - Villa Angostura Neuquén", precision: "area" },
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "refugio-jakob",
    name: "Refugio Jakob / Laguna San Martín",
    aliases: ["Jakob", "Refugio San Martín", "Laguna San Martin"],
    zone: "Catedral - Jakob",
    region: "bariloche",
    type: "refugio",
    lat: -41.1867539,
    lon: -71.5610164,
    altitudeM: null,
    priority: "primary",
    outingTags: ["refugio", "alta-montana", "lago"],
    exposureTags: ["alta-montana", "viento", "roca"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "refugio-italia",
    name: "Refugio Italia / Laguna Negra / Manfredo Segré",
    aliases: ["Refugio Italia", "Laguna Negra", "Manfredo Segre", "Segré"],
    zone: "Colonia Suiza - Laguna Negra",
    region: "bariloche",
    type: "refugio",
    lat: -41.1367041,
    lon: -71.5777839,
    altitudeM: null,
    priority: "primary",
    outingTags: ["refugio", "alta-montana", "laguna"],
    exposureTags: ["alta-montana", "viento", "niebla"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "pampa-linda",
    name: "Pampa Linda",
    aliases: ["Tronador base", "Pampa"],
    zone: "Tronador - Pampa Linda",
    region: "tronador",
    type: "montana",
    lat: -41.2305654,
    lon: -71.7732021,
    altitudeM: null,
    priority: "primary",
    outingTags: ["alta-montana", "glaciar", "base"],
    exposureTags: ["montana", "viento", "precipitacion"],
    windguru: { spotId: 992465, label: "Argentina - Bariloche - Cerro tronador", precision: "nearby" },
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "otto-meiling",
    name: "Refugio Otto Meiling",
    aliases: ["Otto Meiling", "Meiling", "Tronador alto"],
    zone: "Tronador alto",
    region: "tronador",
    type: "refugio",
    lat: -41.1759253,
    lon: -71.8180138,
    altitudeM: null,
    priority: "primary",
    outingTags: ["refugio", "glaciar", "alta-montana"],
    exposureTags: ["alta-montana", "viento", "frio"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "refugio-rocca",
    name: "Refugio Rocca",
    aliases: ["Agostino Rocca", "Rocca", "Paso de las Nubes"],
    zone: "Tronador - Paso de las Nubes",
    region: "tronador",
    type: "refugio",
    lat: -41.1546665,
    lon: -71.8058898,
    altitudeM: null,
    priority: "primary",
    outingTags: ["refugio", "alta-montana", "travesia"],
    exposureTags: ["alta-montana", "viento", "glaciar"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "refugio-piltriquitron",
    name: "Refugio Piltriquitrón",
    aliases: ["Piltriquitron", "Piltri", "Refugio del Piltri"],
    zone: "Piltriquitrón",
    region: "bolson",
    type: "refugio",
    lat: -41.9689585,
    lon: -71.4701407,
    altitudeM: null,
    priority: "primary",
    outingTags: ["refugio", "mirador", "montana"],
    exposureTags: ["montana", "viento", "bosque"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde búsqueda geográfica pública de OpenStreetMap/Nominatim",
    altitudeSource: null
  },
  {
    id: "playa-munoz",
    name: "Playa Muñoz",
    aliases: ["Muñoz", "Playa Munoz"],
    zone: "Brazo Tristeza",
    region: "bariloche",
    type: "montana",
    lat: -41.2194411,
    lon: -71.4333182,
    altitudeM: null,
    priority: "secondary",
    outingTags: ["secundario", "playa", "lago", "trekking"],
    exposureTags: ["lago", "bosque"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde OpenStreetMap/Nominatim para la playa",
    altitudeSource: null
  },
  {
    id: "refugio-frey",
    name: "Refugio Frey",
    aliases: ["Frey", "Laguna Toncek"],
    zone: "Catedral - Frey",
    region: "bariloche",
    type: "refugio",
    lat: -41.1823853,
    lon: -71.4407342,
    altitudeM: null,
    priority: "secondary",
    outingTags: ["secundario", "refugio", "alta-montana"],
    exposureTags: ["roca", "viento", "alta-montana"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde OpenStreetMap/Nominatim para el sendero al refugio",
    altitudeSource: null
  },
  {
    id: "refugio-lopez",
    name: "Refugio López",
    aliases: ["Lopez", "Refugio Lopez"],
    zone: "Bahía López",
    region: "bariloche",
    type: "refugio",
    lat: -41.1022919,
    lon: -71.5596840,
    altitudeM: null,
    priority: "secondary",
    outingTags: ["secundario", "refugio", "montana"],
    exposureTags: ["viento", "mirador", "bosque"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde OpenStreetMap/Nominatim para el refugio",
    altitudeSource: null
  },
  {
    id: "la-buitrera",
    name: "La Buitrera",
    aliases: ["Cerro La Buitrera", "Condorera"],
    zone: "Ñirihuau - La Lucha",
    region: "bariloche",
    type: "montana",
    lat: -41.3039584,
    lon: -71.1593481,
    altitudeM: null,
    priority: "secondary",
    outingTags: ["secundario", "mirador", "trekking"],
    exposureTags: ["viento", "sol", "expuesto"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde OpenStreetMap/Nominatim para La Buitrera (Condorera)",
    altitudeSource: null
  },
  {
    id: "cerro-goye",
    name: "Cerro Goye",
    aliases: ["Goye"],
    zone: "Colonia Suiza",
    region: "bariloche",
    type: "montana",
    lat: -41.1181787,
    lon: -71.5039288,
    altitudeM: null,
    priority: "secondary",
    outingTags: ["secundario", "mirador", "trekking"],
    exposureTags: ["viento", "bosque", "mirador"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde OpenStreetMap/Nominatim para el cerro",
    altitudeSource: null
  },
  {
    id: "valle-encantado",
    name: "Valle Encantado",
    aliases: ["Ruta 237", "Valle"],
    zone: "Ruta 237",
    region: "ruta-237",
    type: "montana",
    lat: -40.7401878,
    lon: -71.1031426,
    altitudeM: null,
    priority: "secondary",
    outingTags: ["secundario", "ruta", "mirador"],
    exposureTags: ["viento", "sol", "roca"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde OpenStreetMap/Nominatim para el tramo turístico de Valle Encantado",
    altitudeSource: null
  },
  {
    id: "manso-steffen",
    name: "Pozones del Manso y Lago Steffen",
    aliases: ["Pozones del Manso", "Lago Steffen", "Manso"],
    zone: "Manso - Steffen",
    region: "manso",
    type: "montana",
    lat: -41.5136867,
    lon: -71.5707409,
    altitudeM: null,
    priority: "secondary",
    outingTags: ["secundario", "rio", "lago", "trekking"],
    exposureTags: ["rio", "bosque", "valle"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde OpenStreetMap/Nominatim para Lago Steffen, usadas como referencia robusta del sector Manso-Steffen",
    altitudeSource: null
  },
  {
    id: "volcan-puyehue",
    name: "Volcán Puyehue",
    aliases: ["Puyehue"],
    zone: "Cordillera norte",
    region: "puyehue",
    type: "montana",
    lat: -40.5834660,
    lon: -72.1123721,
    altitudeM: null,
    priority: "secondary",
    outingTags: ["secundario", "volcan", "alta-montana"],
    exposureTags: ["alta-montana", "viento", "frio"],
    windguru: null,
    coordinatesSource: "Coordenadas curadas desde OpenStreetMap/Nominatim para el volcán",
    altitudeSource: null
  },
  {
    id: "santa-ana-dora",
    name: "Cascada Santa Ana y Dora",
    aliases: ["Santa Ana y Dora", "Cascada Dora", "Cascada Santa Ana"],
    zone: "Paso Samoré",
    region: "angostura",
    type: "montana",
    lat: -40.7186,
    lon: -71.8972,
    altitudeM: null,
    priority: "secondary",
    outingTags: ["secundario", "cascada", "bosque"],
    exposureTags: ["bosque", "humedo", "barro"],
    windguru: null,
    coordinatesSource: "Coordenada media calculada entre los miradores Santa Ana y Dora curados desde OpenStreetMap/Nominatim",
    altitudeSource: null
  }
];

export const timezone = "America/Argentina/Buenos_Aires";
